### PR TITLE
Test flight new designs for attachments preview on chat

### PR DESCRIPTION
**Pull request by Korede612**
# Pull Request Title
### Description
This pull request addresses the New designs for attachments preview on Chat in Issue https://github.com/stakwork/sphinx-mac/issues/409.

### The following are the addressed issues:
- Build the new UI for multi attachments preview on Chat (existing attachment preview supports one attachment at a time and shows over the chat)
- New design shows attachment previews as an expansion of the message field in the bottom bar, allowing to show multiple attachments in a horizontally scrollable area.
- This ticket DOES NOT involve logic related with sending multiple attachments at a time.

## Changes Made
- Assets added
- Localizable strings added
- Storyboard files edited 
- xibs created for new UIs
- Swift files for the corresponding xibs file
- Models created

## Recording Link
- https://www.loom.com/share/2b07fecbe4894500a41482789d0945c2?sid=94b8a5d7-5c70-4629-8586-23d1c52f7c0f
- https://www.loom.com/share/6408dad405c7491c9e962853541804d0?sid=3b9c6065-aebe-4f1d-a9ab-415a5d655c5a

### CODE REVIEW

**Comment by tomastiminskas** [comment]
@Korede612 here are some corrections needed based on the videos you uploaded:
- There's a darker area on the attachments preview in light mode that I'm not sure why is there. The designs show a plain background color on that area (screenshot below)
Screenshot 2024-06-18 at 3 49 05 PM
- The + button inside the attachments preview area should be next to the items on the left side (as on the designs). Not aligned to the right edge of the attachments preview container as in your implementation: it might be needed to make that plus button a last item of the collection view instead of a fixed view in the right side
- The + button inside the attachments preview has no border in the designs and it seems it has a border on your implementation
- It would be great if you can include in the video a multiple text message to see how the new view adapts to that

Finally I saw that you are showing the drag and drop view when tapping on FILE on the new + menu. That is not correct. The drag and drop new design should apply to the existing drag and drop view which automatically shows when dragging a file on the chat view (that logic is already implemented, so the only change needed would be applying the new designs to the existing view). In the next tickets we will do the needed changes so when tapping in the FILE option on the new menu a finder window is shown to allow selecting files from there instead of dragging them (so the 2 ways of attaching a file will be supported). But that logic is out of the scope of this ticket so just focus on the designs for now

**Comment by Korede612** [comment]
## Update Based on Feedback
### Link to the updated recordings
#### Light Mode: 
- https://www.loom.com/share/d501046b56da4740bb1a990b285ca5d4?sid=d8f91590-d7b9-4636-bc74-386a1fd5b8cd
#### Dark Mode: 
- https://www.loom.com/share/1034e148801c4d2a84312b1e946245de?sid=350d73d2-9813-44c8-81d8-261190926708

**Comment by tomastiminskas** [comment]
@Korede612 sorry to keep asking for corrections, but the videos don't match the designs in Figma yet. Once these are fixed I will be able to process the pmts: Here are some details:

- Remove the bottom space between the attachments preview and the text field. In the designs there is no that much margin as in your implementation. Also the left and top margins of the elements in the attachments preview with the container should be the same. Right now it's a bit bigger on the top than on the left

Designs:
Screenshot 2024-06-20 at 9 36 18 AM

-----------------------------
Video:
Screenshot 2024-06-20 at 9 36 53 AM

- Remove the line between those since it's not in the designs
- Remove the border line of the + button inside the attachments preview container (and check the background color of the + button)
- When some attachments are in the attachments preview view, the drag and drop view should be entirely visible. Right now it seems it goes under the attachments preview view to it's cut off (the dotted border line of the drag and drop view is cut off as you can see in the screenshot and it should be visible on the bottom above the attachments preview view)
Video: 
Screenshot 2024-06-20 at 9 40 48 AM

- Finally as I asked in the previous comment, I would need you to include in the video a preview of adding some attachments and also a multiline text in the message field to see if it adapts well to that

**Comment by Korede612** [comment]
## Update on Feedback
- As for the space at the bottom, it is for the progress bar which is hidden for now.

`I am sorry for the back and forth on this PR, although I gave it my best as usual and I believe there is room for improvement.`
<br> **`Thanks for your understanding.`**
### Links to the new recordings
#### Light Mode:
- https://www.loom.com/share/160a27fbbee74bbc890c6f4e2d8c497e?sid=c265c42f-5f89-4814-b596-40e88c8b7a3a
#### Dark Mode:
- https://www.loom.com/share/347ded4c2717453a9b6ddbb2969e5ede?sid=61e24f9c-963e-42ca-85c9-65cb1d9ba854

**Pull request merged**
