### PR TITLE
add notification handler with timeout to address issues

### PR DESCRIPTION
**Pull request by uncleJim21**
record key exchange completion with notification center

### CODE REVIEW

**Comment by tomastiminskas** [comment]
@uncleJim21 is this finished? Some comments about what I saw when reviewing it:
- handleKeyExchangeTimeout is never called (so we are not handling timeout)
- You are posting to didReceiveContactKeyExchange on contactCreate method but you are not actually checking if the inserts is for the user you are trying to connect with and you are not checking if the contact has contactKey set already. 

It seems like at the moment you create the contact and the createContact endpoint call success that post message will be triggered and it could still happen that the contact has no contactKey yet

**Comment by uncleJim21** [comment]
1. handleKeyExchangeTimeout is called when the 30s timeout window expires and the keyExchangeWDT triggers. I think that's the only condition where it's appropriate to call it. Do you agree?
2. Agreed but I see limited upside. The UI itself blocks until the message is sent so I do not think it is possible to be adding more than one contact at a time so it seems like unnecessary tech debt. But if you deem it necessary I will add it.

**Comment by uncleJim21** [comment]
actually I was looking at the wrong codebase iOS Not Mac so scratch #1. I fixed that with the latest push.

**Comment by tomastiminskas** [comment]
Even when you can't create a second contact at the same time you could receive the contact socket message for several reasons. Like if a contact changes his name or profile picture, those values are propagated to all the connected contacts, so you could receive that socket message at any time for different reasons. It is unlikely but I think it's worths it doing the checks. 

On Monday I will review the changes, tests and merge for next releases

**Comment by ecurrencyhodler** [comment]
Closes #126

**Pull request merged**
