### PR TITLE
Join Tribes Window Too Large #95

### PR DESCRIPTION
**Pull request by patgarner**
Also includes fix for constraints conflict due to static width of textfield within the tribe member info view that was expressed when working on this issue. Constraint was modified from being "equals 244" to "great than or equal to 244".

### CODE REVIEW

**Comment by tomastiminskas** [comment]
@patgarner the changes look great. I saw your comment on the ticket. And thanks for fixing the constraints conflict. I would change just one thing if possible so we are consistent on the way we build views on the project. Could you add the NSScrollView directly on the storyboard instead of adding it on the code? The storyboard is `Groups.storyboard`

Thanks in advance

**Comment by patgarner** [comment]
@tomastiminskas Absolutely, good call. I was trying to avoid having to monkey with the constraints setup in the storyboard, but you're right that that's absolutely the right way to do it and I would certainly rather the changes maintain consistency within your codebase.

**Comment by tomastiminskas** [comment]
@patgarner Let me know when they are ready and I will test and merge. Thanks again

**Comment by patgarner** [comment]
@tomastiminskas Ok, I was able to ditch virtually all the code that was added in the view controller with the exception of an NSClipView subclass I added in order to prevent scrolling the content as a side effect when the view/window is resized and in order to keep the content vertically centered when the scrollview grows taller than the content. 

https://github.com/stakwork/sphinx-mac/assets/309928/99125284-43a2-4f9c-9a00-1119f64260f0

**Comment by tomastiminskas** [comment]
@patgarner I merged the PR. Just had to fix the background color of the scroll view and the box that contains the button. They were really simple changes and I want to create a new release, this is why I didn't ask you for the changes since that would delay the release. But letting you know so you are aware of always testing and checking colors when adding new UI elements (since by default they are added with default background colors)

**Comment by patgarner** [comment]
@tomastiminskas Got it. Sorry I missed that, I would have been more than happy to take care of it right away. Nevertheless I'll be sure to watch out for that in the future, thanks for letting me know!

**Pull request merged**
