### PR TITLE
Address issue #21

### PR DESCRIPTION
**Pull request by jimBeaux27**

### CODE REVIEW

**Review by kevkevinpal — APPROVED** [review]
If you could just remove the changes in `sphinx.xcodeproj/project.pbxproj`

otherwise it looks good to me @tomastiminskas if you wanna take a look then merge 

LGTM 🚀

**Comment by tomastiminskas** [comment]
@jimBeaux27 @kevkevinpal agree on removing the project file changes. Then it looks good. I will merge and include it on next release

**Comment by jimBeaux27** [comment]
Thanks @kevkevinpal I reverted the pbxproj file. Let me know if you need anything else.

Cheers,
Jim

**Review by kevkevinpal — APPROVED** [review]
Nice also good idea adding it to the gitignore file

**Comment by tomastiminskas** [comment]
@kevkevinpal @jimBeaux27 I was testing this and it's not working as expected. Right now the Second Brain window is filling the entire screen when it should match the same size and position that the Sphinx main window. 

@jimBeaux27 you should take the frame and position/origin from the `NSApplication.shared.keyWindow`. Let me know when it's done and I will test again and merge

**Comment by jimBeaux27** [comment]
Sounds good @tomastiminskas i made the changes & it seems to work

**Pull request merged**
