### PR TITLE
Reply message fix while changing chat profiles

### PR DESCRIPTION
**Pull request by rashidmustafa**
Fixed an issue where the replyable message was hidden when switching between chat profiles.

### CODE REVIEW

**Comment by tomastiminskas** [comment]
@rashidmustafa I was testing your changes and I found 2 issues that I will detail below:
- When going back to a chat where a reply was saved, the reply view shows up, but the scroll position doesn't adjust so the reply view overlaps the last message (attaching screenshots of how it looks and how it should look)
- When going back to a chat where a reply was saved, the reply view shows up but if you write a message and send it the message is not replying to the message saved (it's like the UI works but not the logic behind). This should be fix setting `newChatViewModel.replyingTo = message`

How it looks now:
Screenshot 2024-01-25 at 10 12 53

How it should look:
Screenshot 2024-01-25 at 10 13 04

View of second issues:
https://github.com/stakwork/sphinx-mac/assets/2242281/b19beecc-81ee-4d69-b48d-0ee76038bfc6

**Comment by tomastiminskas** [comment]
Also @rashidmustafa you should avoid pushing changes like DEVELOPMENT TEAM and BUNDLE ID to the branch you will ask to be merged

**Comment by rashidmustafa** [comment]
@tomastiminskas  issue fixed. Please have a look into this.

**Comment by tomastiminskas** [comment]
@rashidmustafa thanks! They are both fixed now. I will merge and include this in a new release later today or tomorrow

**Pull request merged**
